ARG ROS_DISTRO=noetic
FROM ov2slam-${ROS_DISTRO}-dependencies

ADD . /ws/src/ov2slam

WORKDIR /ws/src/ov2slam

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        libgoogle-glog-dev libgflags-dev \
        libatlas-base-dev \
        libeigen3-dev  \
        libsuitesparse-dev  \
    && rm -rf /var/lib/apt/lists/* \
    && sh ./build_thirdparty.sh

WORKDIR /ws/

RUN . /opt/ros/$ROS_DISTRO/setup.sh && catkin_make



