%YAML 1.0
---

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Set to 1 to read images from folder
read_images_from_folder: 1
fps: 30.0 # Frames per second (only needed if read_images_from_folder is set to 1)

Camera.topic_left: PATH_TO_FOLDER
Camera.topic_right: PATH_TO_FOLDER

Camera.model_left: pinhole
Camera.model_right: pinhole

Camera.left_nwidth: 1241
Camera.left_nheight: 376

Camera.right_nwidth: 1241
Camera.right_nheight: 376

# Camera calibration and distortion parameters (OpenCV) 
Camera.fxl: 718.856
Camera.fyl: 718.856
Camera.cxl: 607.1928
Camera.cyl: 185.2157

Camera.k1l: 0.
Camera.k2l: 0.
Camera.p1l: 0.
Camera.p2l: 0.

Camera.fxr: 718.856
Camera.fyr: 718.856
Camera.cxr: 607.1928
Camera.cyr: 185.2157

Camera.k1r: 0.
Camera.k2r: 0.
Camera.p1r: 0.
Camera.p2r: 0.


# Camera Extrinsic parameters T_b_ci ( v_b = T_b_ci * v_ci )
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1., 0., 0., 0.,
          0., 1., 0., 0.,
          0., 0., 1., 0.,
           0., 0., 0., 1.]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1., 0., 0., 0.537165718864418,
          0., 1., 0., 0.,
          0., 0., 1., 0.,
           0., 0., 0., 1.]

#--------------------------------------------------------------------------------------------
# SLAM Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
debug: 0
log_timings: 0

mono: 0
stereo: 1

force_realtime: 0

# Estimator Mode
slam_mode: 1


# Loop Closing mode
buse_loop_closer: 1

# Stereo rectify or not
bdo_stereo_rect: 1
alpha: 0.

# Init / KF px th.
finit_parallax: 20.


# Features Extractor
use_shi_tomasi: 0
use_fast: 0
use_brief: 1
use_singlescale_detector: 1

# Min dist between kps (define the number of kps)
nmaxdist: 35

# Features quality th.
nfast_th: 10
dmaxquality: 0.001 # used for gftt or singlescale

# Pre-processing
use_clahe: 1
fclahe_val: 2

# KLT related settings.
do_klt: 1
klt_use_prior: 1
btrack_keyframetoframe: 0
nklt_win_size: 9
nklt_pyr_lvl: 3

# Opencv Default: 30 iters. + 0.01 prec.
nmax_iter: 30
fmax_px_precision: 0.01

fmax_fbklt_dist: 0.5
nklt_err: 30.

# Matching th.
bdo_track_localmap: 1

fmax_desc_dist: 0.2 #0.35 # Ratio from desc size (for binary desc.) 
fmax_proj_pxdist: 2.

# Randomize RANSAC?
doepipolar: 1
dop3p : 0
bdo_random: 1
nransac_iter: 100
fransac_err: 3.

# Reproj err th.
fmax_reproj_err: 3.
buse_inv_depth: 1

# Ceres related parameters
robust_mono_th: 5.9915 # (20% : 3.2189 / 10% :  4.6052 / 5% : 5.9915 / 2%: 7.8240 / 1%: 9.2103)  

use_sparse_schur: 1
use_dogleg: 0
use_subspace_dogleg: 0
use_nonmonotic_step: 0

# Estimator parameters
apply_l2_after_robust: 1

nmin_covscore: 25 # Min co-obs for optimizing in SLAM mode BA


# Map Filtering
fkf_filtering_ratio: 0.95

# Final Pass
do_full_ba: 0